version: "3.8"

services:
  discord-lavamusic:
    container_name: discord-lavamusic
    depends_on:
      - discord-lavalink
    deploy:
      restart_policy:
        condition: always
        delay: 5s
    env_file: lavamusic.env
    image: "ghcr.io/brblacky/lavamusic:main"
    labels:
      com.centurylinklabs.watchtower.enable: "true"
      traefik.enable: "false"

networks:
  external:
    external: true
    name: $NETWORK
