version: "3.8"

services:
  discord-lavamusic:
    command: bash -c "apt-get update -y && apt-get install -y openssl && npx prisma generate && node dist/index.js"
    container_name: discord-lavamusic
    depends_on:
      - discord-lavalink
    deploy:
      restart_policy:
        condition: always
        delay: 5s
    env_file: lavamusic.env
    image: ghcr.io/brblacky/lavamusic:v3.2.0
    labels:
      com.centurylinklabs.watchtower.enable: "true"
      traefik.enable: "false"

networks:
  external:
    external: true
    name: $NETWORK
